hyper_paramaters:
  save_hparam: true
  hparam_file: "conf/hparam.yaml"

  hparam_log_file: "C:/Users/Freddie/Documents/PhD/Data/Results/21_20210506_1331_Personalisation_Control/hparam.log"
  hparam_result_file: "C:/Users/Freddie/Documents/PhD/Data/Results/21_20210506_1331_Personalisation_Control/result.log"

hardware_setup:
  use_gpu: true
  random_seed: 13

data:
  folder: "C:/Users/Freddie/Documents/PhD/Data/Results/21_20210506_1331_Personalisation_Control/Data/Activities_Split"

  test_train_split: "@HP_TEST_TRAIN_SPLIT"
  verbose: true

  percentage_train: 70
  max_label_difference: 1

  episode_offset: "@HP_EPISODE_OFFSET"
  training_samples: "@HP_TRAINING_SAMPLES"
  test_samples: 5000

  x_validation_exclude: "@HP_VALIDATION_INCLUDE"

  data_settings:
    num_timesteps: "@HP_TIMESTEPS"
    num_labels: "@HP_NUMBER_ACTIVITIES"
    skip: 2
    normalize: false
    label_heading: "activity"
    data_headings:
      - "r_ankle_accel_x"
      - "r_ankle_accel_y"
      - "r_ankle_accel_z"
      - "r_ankle_gyro_x"
      - "r_ankle_gyro_y"
      - "r_ankle_gyro_z"
      # - "r_ankle_magn_x"
      # - "r_ankle_magn_y"
      # - "r_ankle_magnz"
      - "l_ankle_accel_x" # = r
      - "l_ankle_accel_y" # = -r
      - "l_ankle_accel_z" # = r
      - "l_ankle_gyro_x" # = -r
      - "l_ankle_gyro_y" # = r
      - "l_ankle_gyro_z" # = -r

    label_mapping:
      0: 0 # Walking
      1: 1 # Ramp Ascent
      2: 2 # Ranp Descent
      3: 3 # Stair Ascent
      4: 4 # Stair Descent
      5: 5 # Stop
      # # 6: 4 # Transition
model:
  config_file: "conf/model.yaml"

loss_func:
  type: "categorical_crossentropy"
  settings:
    from_logits: true

compile:
  optimizer: "adam"
  metrics:
    - "categorical_accuracy"

callbacks:
  use_tensorboard: true
  tensorboard:
    histogram_freq: 1

  use_early_stopping_threshold: false
  early_stopping_threshold: 0.96

  use_early_stopping: true
  early_stopping:
    monitor: "val_loss"
    verbose: 1
    patience: 3

  use_save_model: true
  save_model:
    verbose: 1
    save_weights_only: true
    period: 5

fit:
  batch_size: 500
  epochs: 1000
  shuffle: true
  # steps_per_epoch: 5 # 50 windows per epoch
  # verbose: 2

save:
  config: true
  final_model: true

  config_dir: "logs/conf/"
  tensorboard_dir: "logs/scalars/"
  model_dir: "logs/model/"
  history_dir: "logs/history/"
