hyper_paramaters:
  save_hparam: true
  hparam_file: "conf/hparam.yaml"

  hparam_log_file: "C:/Users/Freddie/Documents/PhD/Data/Results/18_20201116_1129_transition_state/hparam.log"
  hparam_result_file: "C:/Users/Freddie/Documents/PhD/Data/Results/18_20201116_1129_transition_state/result.log"

hardware_setup:
  use_gpu: true
  random_seed: 13

data:
  folder: "C:/Users/Freddie/Documents/PhD/Data/Results/18_20201116_1129_transition_state/Data/100hz_no_tran"
  # folder: "C:/Users/Freddie/Documents/PhD/Data/Results/18_20201116_1129_transition_state/Data/100hz_transition"

  test_train_split: 0.7
  load_augment: false
  verbose: false

  percentage_train: 1
  max_label_difference: 1.5

  x_validation_exclude: "@HP_X_VALIDATION_EXCLUDE"
  x_validation_include: "@HP_X_VALIDATION_INCLUDE"
  x_participant_count: "@HP_PARTICINPANT_COUNT"

  data_settings:
    num_timesteps: "@HP_TIMESTEPS"
    num_labels: "@HP_NUMBER_ACTIVITIES"
    skip: 1
    normalize: false
    label_heading: "activity"
    data_headings:
      - "r_ankle_accel_x" # Forward
      - "r_ankle_accel_y"
      - "r_ankle_accel_z"
      - "r_ankle_gyro_x"
      - "r_ankle_gyro_y" # Saggital
      - "r_ankle_gyro_z"
      # - "r_ankle_magn_x"
      # - "r_ankle_magn_y"
      # - "r_ankle_magnz"
    label_mapping:
      0: 0 # Walking
      1: 1 # Ramp Ascent
      2: 2 # Ranp Descent
      3: 3 # Stair Ascent
      4: 4 # Stair Descent
      5: 5 # Stop
      # 6: 4 # Transition
model:
  config_file: "conf/model.yaml"

loss_func:
  type: "categorical_crossentropy"
  settings:
    from_logits: true

compile:
  optimizer: "adam"
  metrics:
    - "categorical_accuracy"

callbacks:
  use_tensorboard: true
  tensorboard:
    histogram_freq: 1

  use_early_stopping: true
  early_stopping:
    monitor: "val_loss"
    verbose: 1
    patience: 5

  use_save_model: true
  save_model:
    verbose: 1
    save_weights_only: true
    period: 5

fit:
  batch_size: 2000
  epochs: 1000
  shuffle: true
  verbose: 2

save:
  config: true
  final_model: true

  config_dir: "logs/conf/"
  tensorboard_dir: "logs/scalars/"
  model_dir: "logs/model/"
  history_dir: "logs/history/"
