hardware_setup:
  use_gpu: true
  random_seed: 0

data:
  folder: "Data_3_state"
  test_train_split: 0.7

  percentage_train: 1

  data_settings:
    num_timesteps: 128
    label_heading: "activity"
    data_headings:
      - "r_ankle_accel_x"
      - "r_ankle_accel_y"
      - "r_ankle_accel_z"
      - "r_ankle_gyro_x"
      - "r_ankle_gyro_y"
      - "r_ankle_gyro_z"
      # - "r_ankle_magn_x"
      # - "r_ankle_magn_y"
      # - "r_ankle_magnz"
      # - "l_ankle_accel_x"
      # - "l_ankle_accel_y"
      # - "l_ankle_accel_z"
      # - "l_ankle_gyro_x"
      # - "l_ankle_gyro_y"
      # - "l_ankle_gyro_z"
      # - "l_ankle_magn_x"
      # - "l_ankle_magn_y"
      # - "l_ankle_magnz"
      # - "r_hip_accel_x"
      # - "r_hip_accel_y"
      # - "r_hip_accel_z"
      # - "r_hip_gyro_x"
      # - "r_hip_gyro_y"
      # - "r_hip_gyro_z"
      # - "r_hip_magn_x"
      # - "r_hip_magn_y"
      # - "r_hip_magnz"
      # - "l_hip_accel_x"
      # - "l_hip_accel_y"
      # - "l_hip_accel_z"
      # - "l_hip_gyro_x"
      # - "l_hip_gyro_y"
      # - "l_hip_gyro_z"
      # - "l_hip_magn_x"
      # - "l_hip_magn_y"
      # - "l_hip_magnz"
      # - "chest_accel_x"
      # - "chest_accel_y"
      # - "chest_accel_z"
      # - "chest_gyro_x"
      # - "chest_gyro_y"
      # - "chest_gyro_z"
      # - "chest_magn_x"
      # - "chest_magn_y"
      # - "chest_magnz"

    num_labels: 3
    skip: 1

model:
  config_file: "conf/model.yaml"

loss_func:
  type: "categorical_crossentropy"
  settings:
    from_logits: true

compile:
  optimizer: "adam"
  metrics:
    - "categorical_accuracy"

callbacks:
  use_tensorboard: true
  tensorboard:
    histogram_freq: 1

  use_early_stopping: true
  early_stopping:
    monitor: "val_loss"
    verbose: 1
    patience: 5

  use_save_model: true
  save_model:
    verbose: 1
    save_weights_only: true
    period: 5

fit:
  batch_size: 500
  epochs: 1000
  shuffle: true

save:
  config_dir: "logs/conf/"
  tensorboard_dir: "logs/scalars/"
  model_dir: "logs/model/"
  history_dir: "logs/history/"
